import fs from 'node:fs/promises';
import path from 'node:path';
import { rollup, type OutputChunk } from 'rollup';
import dts from 'rollup-plugin-dts';
import ts from 'typescript';
import type { PipelineContext } from '@somedayyoung/core';

function deduplicateOrvalHeaders(source: string): string {
  const scanner = ts.createScanner(
    ts.ScriptTarget.Latest,
    false,
    ts.LanguageVariant.Standard,
    source,
  );
  const duplicateHeaders: Array<{ start: number; end: number }> = [];
  let foundHeader = false;

  for (
    let token = scanner.scan();
    token !== ts.SyntaxKind.EndOfFileToken;
    token = scanner.scan()
  ) {
    const comment = scanner.getTokenText();
    if (
      token === ts.SyntaxKind.MultiLineCommentTrivia &&
      comment.includes('Generated by orval') &&
      comment.includes('Do not edit manually.')
    ) {
      if (foundHeader) {
        duplicateHeaders.push({
          start: scanner.getTokenPos(),
          end: scanner.getTextPos(),
        });
      }
      foundHeader = true;
    }
  }

  return duplicateHeaders
    .reverse()
    .reduce(
      (result, header) =>
        result.slice(0, header.start) + result.slice(header.end),
      source,
    );
}

export async function generateSingleModels(
  context: PipelineContext,
  file: string,
): Promise<void> {
  const parsedPath = path.parse(file);
  const modelsDir = path.join(
    context.outputDir,
    parsedPath.dir,
    parsedPath.name,
  );
  const bundle = await rollup({
    input: path.join(modelsDir, 'index.ts'),
    plugins: [dts()],
  });
  const { output } = await bundle.generate({ format: 'es' });
  await bundle.close();
  const [chunk] = output as OutputChunk[];

  await fs.writeFile(
    path.join(context.outputDir, file),
    deduplicateOrvalHeaders(chunk.code),
    'utf8',
  );
  await fs.rm(modelsDir, {
    recursive: true,
    force: true,
  });
}
